

export const getProducts=()=>{
    try{}
    catch(error){
        console.log('Error while calling getProducts.api', error.message);
    }
}